# open(nombre,modo)
#----------------------------------------------------

#recordar hacer en la consola de CMD "pip install ipdb"
#----------------------------------
def hangman2(Intentos):
	
	if Intentos == 5:
		print("(̅_̅_̅(̅_̅_̅_̅_̅_̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅()")
		print("█         |")
		print("█         |")
		print("█  ")
		print("█   ")
		print("█ ")
		print("█ ")
		print("█  ")
		print("█  ")
		print("█")
		print("█")
		print("█")
		print("█")
		print("█")
		print("██████████████████████████")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 4:
		print("(̅_̅_̅(̅_̅_̅_̅_̅_̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅()")
		print("█        |")
		print("█        |")
		print("█      (̲̅̅●̲̲̅̅̅̅=̲̲̅̅̅̅●̲̅̅)")
		print("█   ")
		print("█ ")
		print("█  ")
		print("█  ")
		print("█  ")
		print("█")
		print("█")
		print("█")
		print("█")
		print("█")
		print("██████████████████████████")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 3:
		print("(̅_̅_̅(̅_̅_̅_̅_̅_̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅()")
		print("█        |")
		print("█        |")
		print("█      (̲̅̅●̲̲̅̅̅̅=̲̲̅̅̅̅●̲̅̅)")
		print("█        ║  ")
		print("█        ║")
		print("█        ║ ")
		print("█ ")
		print("█ ")
		print("█")
		print("█")
		print("█")
		print("█")
		print("█")
		print("██████████████████████████")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 2:
		print("(̅_̅_̅(̅_̅_̅_̅_̅_̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅()")
		print("█        |")
		print("█        |")
		print("█      (̲̅̅●̲̲̅̅̅̅=̲̲̅̅̅̅●̲̅̅)")
		print("█       /║\ ")
		print("█      / ║ \     ")
		print("█        ║ ")
		print("█ ")
		print("█ ")
		print("█")
		print("█")
		print("█")
		print("█")
		print("█")
		print("██████████████████████████")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 1:
		print("(̅_̅_̅(̅_̅_̅_̅_̅_̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅()")
		print("█        |")
		print("█        |")
		print("█     \(̲̅̅●̲̲̅̅̅̅=̲̲̅̅̅̅●̲̅̅)   hi")
		print("█      \/║\ ")
		print("█        ║ \  ")
		print("█        ║ ")
		print("█       / \ ")
		print("█      /   \ ")
		print("█")
		print("█")
		print("█")
		print("█")
		print("█")
		print("██████████████████████████")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 0:
		print("(̅_̅_̅(̅_̅_̅_̅_̅_̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅_̅_̅̅()")
		print("█        |")
		print("█        |")
		print("█       (̲̅xx)  dwaaaughhh")
		print("█       /║\ ")
		print("█      / ║ \       YOU DIE!!!")
		print("█        ║  ")
		print("█       / \ ")
		print("█      /   \ ")
		print("█")
		print("█")
		print("█")
		print("█")
		print("█")
		print("██████████████████████████")
		print("Intentos restantes: ", Intentos)

def hangman(Intentos):
	
	if Intentos == 5:
		print("▄▄▄▄▄▄▄")
		print("▓  ")
		print("▓  ")
		print("▓  ")
		print("▓ ")
		print("▓")
		print("▓") 
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄'esto.es.un.piso'")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 4:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
		print("▓       █ ")
		print("▓   |^^^^^^^|")
		print("▓   |       | ")
		print("▓   |__   __| ")	
		print("▓   ( .\ (. )")	
		print("▓   @   (_) @")		
		print("▓   /       \ ")						
		print("▓   \`-----'' ")
		print("▓    \ \___/ ")
		print("▓")
		print("▓") 
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄'esto.es.un.piso'")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 3:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄ ")
		print("▓       █ ")
		print("▓   |^^^^^^^|")
		print("▓   |       | ")
		print("▓   |__   __| ")	
		print("▓   ( .\ (. )")	
		print("▓   @   (_) @")		
		print("▓   /       \ ")						
		print("▓   \`-----'' ")
		print("▓    \ \___/ ")
		print("▓    _ |__| _ ")
		print("▓   /        \ ")
		print("▓   |        | ")
		print("▓   |        |")
		print("▓   |________|")		
		print("▓ ")
		print("▓")
		print("▓") 
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄'esto.es.un.piso'")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 2:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄ ")
		print("▓         █ ")
		print("▓     |^^^^^^^|")
		print("▓     |       | ")
		print("▓     |__   __| ")	
		print("▓     ( .\ (. )")	
		print("▓    @   (_) @")		
		print("▓     /       \ ")						
		print("▓     \`-----'' ")
		print("▓      \ \___/ ")
		print("▓      _ |__| _ ")
		print("▓     /        \ ")
		print("▓   / |        | ")
		print("▓  / /|        |")
		print("▓  \ \|________|")	
		print("▓ ")
		print("▓")
		print("▓") 
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄'esto.es.un.piso'")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 1:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
		print("▓         █ ")
		print("▓     |^^^^^^^|")
		print("▓     |       | ")
		print("▓     |__   __| ")	
		print("▓     ( .\ (. )")	
		print("▓    @   (_) @")		
		print("▓     /       \ ")						
		print("▓     \`-----'' ")
		print("▓      \ \___/ ")
		print("▓      _ |__| _ ")
		print("▓     /        \ ")
		print("▓   / |        | \ ")
		print("▓  / /|        |\ \ ")
		print("▓  \ \|________|/ /")	
		print("▓ ")
		print("▓")
		print("▓") 
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄'esto.es.un.piso'")
		print("Intentos restantes: ", Intentos)
	elif Intentos == 0:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
		print("▓         █ ")
		print("▓     |^^^^^^^|")
		print("▓     |       | ")
		print("▓     |__   __| ")	
		print("▓     ( .\ (. )")	
		print("▓    @   (_) @")		
		print("▓     /       \ ")						
		print("▓     \`-----'' ")
		print("▓      \ \___/ ")
		print("▓      _ |__| _ ")
		print("▓     /        \ ")
		print("▓   / |        | \ ")
		print("▓  / /|        |\ \ ")
		print("▓  \ \|________|/ /	 YOU DIE!!!")
		print("▓     |        |")
		print("▓     |    |   |")
		print("▓     |____|___|")
		print("▓       | | | |")
		print("▓      _|_| |_|_ ")		
		print("▓     (___| |___) ")
		print("▓")
		print("▓") 
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄'esto.es.un.piso'")
		print("Intentos restantes: ", Intentos)