

import ImprimirEspaciado


def hangman(Intentos, incognitaGuion):
	
	if Intentos == 7:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄","\tIntentos restantes: ", Intentos)
		print("▓  ")
		print("▓  ")
		print("▓  ")
		print("▓ ")
		print("▓")
		print("▓") 
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",ImprimirEspaciado.ImprimirEspaciado(incognitaGuion))
		
	elif Intentos == 6:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄","\tIntentos restantes: ", Intentos)
		print("▓       █ ")
		print("▓   |^^^^^^^|")
		print("▓   |       | ")
		print("▓   |__   __| ")	
		print("▓   ( .\ (. )")	
		print("▓   @   (_) @")		
		print("▓   /       \ ")						
		print("▓   \`-----'' ")
		print("▓    \ \___/ ")
		print("▓")
		print("▓") 
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",ImprimirEspaciado.ImprimirEspaciado(incognitaGuion))
		
	elif Intentos == 5:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄","\tIntentos restantes: ", Intentos)
		print("▓       █ ")
		print("▓   |^^^^^^^|")
		print("▓   |       | ")
		print("▓   |__   __| ")	
		print("▓   ( .\ (. )")	
		print("▓   @   (_) @")		
		print("▓   /       \ ")						
		print("▓   \`-----'' ")
		print("▓    \ \___/ ")
		print("▓    _ |__| _ ")
		print("▓   /        \ ")
		print("▓   |        | ")
		print("▓   |        |")
		print("▓   |________|")		
		print("▓ ")
		print("▓")
		print("▓") 
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",ImprimirEspaciado.ImprimirEspaciado(incognitaGuion))
		
	elif Intentos == 4:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄","\tIntentos restantes: ", Intentos)
		print("▓         █ ")
		print("▓     |^^^^^^^|")
		print("▓     |       | ")
		print("▓     |__   __| ")	
		print("▓     ( .\ (. )")	
		print("▓    @   (_) @")		
		print("▓     /       \ ")						
		print("▓     \`-----'' ")
		print("▓      \ \___/ ")
		print("▓      _ |__| _ ")
		print("▓     /        \ ")
		print("▓   / |        | ")
		print("▓  / /|        |")
		print("▓  \ \|________|")	
		print("▓ ")
		print("▓")
		print("▓") 
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",ImprimirEspaciado.ImprimirEspaciado(incognitaGuion))
		
	elif Intentos == 3:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄","\tIntentos restantes: ", Intentos)
		print("▓         █ ")
		print("▓     |^^^^^^^|")
		print("▓     |       | ")
		print("▓     |__   __| ")	
		print("▓     ( .\ (. )")	
		print("▓    @   (_) @")		
		print("▓     /       \ ")						
		print("▓     \`-----'' ")
		print("▓      \ \___/ ")
		print("▓      _ |__| _ ")
		print("▓     /        \ ")
		print("▓   / |        | \ ")
		print("▓  / /|        |\ \ ")
		print("▓  \ \|________|/ /")	
		print("▓ ")
		print("▓")
		print("▓") 
		print("▓")
		print("▓")
		print("▓")
		print("▓")
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",ImprimirEspaciado.ImprimirEspaciado(incognitaGuion))
		
	elif Intentos == 2:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄","\tIntentos restantes: ", Intentos)
		print("▓         █ ")
		print("▓     |^^^^^^^|")
		print("▓     |       | ")
		print("▓     |__   __| ")	
		print("▓     ( .\ (. )")	
		print("▓    @   (_) @")		
		print("▓     /       \ ")						
		print("▓     \`-----'' ")
		print("▓      \ \___/ ")
		print("▓      _ |__| _ ")
		print("▓     /        \ ")
		print("▓   / |        | \ ")
		print("▓  / /|        |\ \ ")
		print("▓  \ \|________|/ /	           ")
		print("▓     |        |")
		print("▓     |    |   |")
		print("▓     |____|___|")
		print("▓              ")
		print("▓                ")		
		print("▓                 ")
		print("▓")
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",ImprimirEspaciado.ImprimirEspaciado(incognitaGuion))
		
		
	elif Intentos == 1:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄","\tIntentos restantes: ", Intentos)
		print("▓         █ ")
		print("▓     |^^^^^^^|")
		print("▓     |       | ")
		print("▓     |__   __| ")	
		print("▓     ( .\ (. )")	
		print("▓    @   (_) @")		
		print("▓     /       \ ")						
		print("▓     \`-----'' ")
		print("▓      \ \___/ ")
		print("▓      _ |__| _ ")
		print("▓     /        \ ")
		print("▓   / |        | \ ")
		print("▓  / /|        |\ \ ")
		print("▓  \ \|________|/ /	 ")
		print("▓     |        |")
		print("▓     |    |   |")
		print("▓     |____|___|")
		print("▓           | |")
		print("▓           |_|_ ")		
		print("▓           |___) ")
		print("▓")
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",ImprimirEspaciado.ImprimirEspaciado(incognitaGuion))
		

	elif Intentos == 0:
		print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄","\tIntentos restantes: ", Intentos)
		print("▓         █ ")
		print("▓     |^^^^^^^|")
		print("▓     |       | ")
		print("▓     |__   __| ")	
		print("▓     ( .\ (. )")	
		print("▓    @   (_) @")		
		print("▓     /       \ ")						
		print("▓     \`-----'' ")
		print("▓      \ \___/ ")
		print("▓      _ |__| _ ")
		print("▓     /        \ ")
		print("▓   / |        | \ ")
		print("▓  / /|        |\ \ ")
		print("▓  \ \|________|/ /	 YOU DIE!!!")
		print("▓     |        |")
		print("▓     |    |   |")
		print("▓     |____|___|")
		print("▓       | | | |")
		print("▓      _|_| |_|_ ")		
		print("▓     (___| |___) ")
		print("▓")
		print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",ImprimirEspaciado.ImprimirEspaciado(incognitaGuion))
		